version: "3.8"
services:
   elasticsearch1:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
     labels:
       co.elastic.logs/module: elasticsearch
#     volumes:
#       - esdata01:/usr/share/elasticsearch/data
     environment:
       - node.name=elasticsearch1
       - cluster.name=evk
       - xpack.security.enabled=false
       - discovery.seed_hosts=elasticsearch2
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - cluster.initial_master_nodes=elasticsearch1
     ulimits:
       memlock:
         soft: -1
         hard: -1
     ports:
      - "9200:9200"
     networks:
       - esnet
   elasticsearch2:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
     labels:
       co.elastic.logs/module: elasticsearch
#     volumes:
#       - esdata01:/usr/share/elasticsearch/data
     environment:
       - node.name=elasticsearch2
       - cluster.name=evk
       - xpack.security.enabled=false
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - discovery.seed_hosts=elasticsearch1
       - cluster.initial_master_nodes=elasticsearch1
     networks:
       - esnet
     ulimits:
       memlock:
         soft: -1
         hard: -1
networks:
 esnet:
   driver: bridge